### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'acquirer' in 'field list', query was: SELECT qpstat, transaction, cardtype, cardnumber, acquirer, is_3d_secure, currency FROM quickpaypayment_order_status WHERE ordernum = :order_number

### ISSUE THREAD

**Issue by tobbecokta** [RBech/Quickpay_Payment#11]
Hi,

I just installed version 3.4.5 on Magento 1.9.3.2. The server is running mysql 5.6 and PHP 5.7.

When i try to make a test order i get the following error message:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'acquirer' in 'field list', query was: SELECT qpstat, transaction, cardtype, cardnumber, acquirer, is_3d_secure, currency FROM quickpaypayment_order_status WHERE ordernum = :order_number`

**Comment by tobbecokta** [comment]
This is the URL visible in the web browser. The page is just blank. The error message is sent to me through email.

/se/checkouts/index/saveOrder/

**Comment by tobbecokta** [comment]
Managed to get the error log. Please see below:

```
a:5:{i:0;s:153:"{"message":"Validation error: order_id already exists on another payment","errors":{"order_id":["already exists on another payment"]},"error_code":"400"}";i:1;s:2233:"#0 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/community/Quickpay/Payment/Helper/Data.php(41): Mage::throwException('{"message":"Val...')
#1 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/community/Quickpay/Payment/Helper/Data.php(153): Quickpay_Payment_Helper_Data->request('payments', Array, '')
#2 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/design/frontend/base/default/template/quickpaypayment/payment/redirect.phtml(32): Quickpay_Payment_Helper_Data->qpCreatePayment(Object(Mage_Sales_Model_Order))
#3 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/216361.cl...')
#4 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#5 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#6 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#7 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/community/Quickpay/Payment/controllers/PaymentController.php(31): Mage_Core_Block_Abstract->toHtml()
#8 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Quickpay_Payment_PaymentController->redirectAction()
#9 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('redirect')
#10 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /home/216361.cloudwaysapps.com/tjgtaadqkd/public_html/index.php(102): Mage::run('', 'store')
#14 {main}";s:3:"url";s:37:"/se/quickpaypayment/payment/redirect/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"se";}
```


This seems to be the same error as reported in this thread https://github.com/RBech/Quickpay_Payment/issues/7
